Add merchant name alias
QIWI-API/qiwi-payment-widgets pull request #22
Opened 2019-07-03 15:37 UTC by artiemq

2019-07-04 08:27 UTC, magicwolf9 commented on src/components/Title/Title.js
> +                component.changeTitle(data.widgetStyles['PAY_FORM_MERCHANT_NAME'] && data.widgetMerchantName);
styleCode.PAY_FORM_MERCHANT_NAME

2019-07-04 09:12 UTC, Khromushkin requested changes

2019-07-04 09:12 UTC, Khromushkin commented on src/components/Title/Title.js
> +                component.changeTitle(data.widgetStyles['PAY_FORM_MERCHANT_NAME'] && data.widgetMerchantName);
а почему && то? если нет в widgetStyles, то отобразить на форме 'undefined'? =)

2019-07-08 11:19 UTC, magicwolf9 approved these changes

2019-07-08 13:34 UTC, merged